name: thecomfortablemind
favicon: null
layout_spectrum: 0.8202882527839392
typography_spectrum: 0.761930552078411
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d3d3'
    - '#353036'
    - '#8f778d'
    - '#bfa398'
    - '#ac5c37'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.5602781309280545
  rhythmicContrast: 1
purpose: []
